dataset: liveness
batch_size: 256
checkpoints: [
   /mnt/lustre/tiankeyu/htl_ckpt/DF_MTL_LV1_10_R50_re_convertBB.pth.tar,
   /mnt/lustre/tiankeyu/htl_ckpt/GS_MTL_LV1_10_and_LV2eve_R50_convertBB.pth.tar,
   /mnt/lustre/tiankeyu/htl_ckpt/GS_MTL_LV1_10_and_LV2eve_Xformer_R50_convertBB.pth.tar,
   /mnt/lustre/tiankeyu/htl_ckpt/GS_MTL_LV1_10_and_LV2eve_4K_R50_convertBB.pth.tar,
   /mnt/lustre/tiankeyu/htl_ckpt/GS_MTL_LV1_10_and_LV2eve_4K_and_LV3clip_R50_convertBB.pth.tar,
   /mnt/lustre/tiankeyu/htl_ckpt/YG_clip_res50_yfcc15m_convertBB.pth,
   /mnt/lustre/tiankeyu/htl_ckpt/clip_res50_50M_noLiveness_convertBB.pth.tar,
   /mnt/lustre/tiankeyu/htl_ckpt/xueshuClip.pth.tar,
]   # should be no more than num_gpus
n_neighbors: 12
train_set: False
calc_hx: False
